import { ProjectFeature, Agreement } from './types';

export const AGREEMENTS: Agreement[] = [
  {
    id: 'ce47-2022-ge',
    name: 'CE 47/2022 (GE)',
    description: 'LPMit Programme - Landslip Prevention and Mitigation Works',
  },
  {
    id: 'ce53-2022-ge',
    name: 'CE 53/2022 (GE)',
    description: 'LPMit Programme - Landslip Prevention and Mitigation Works (HK Island)',
  },
];

export const MOCK_DATA: ProjectFeature[] = [
  // === Row 1 ===
  {
    id: '1', no: 1, agreement: 'CE 47/2022 (GE)',
    location: "West of Tin's Centre Block 9, Hung Cheung Road, Tuen Mun",
    featureNo: '5SE-B/C203',
    s3rStatus: 'Final S3R Accepted 5 Aug 2024', s3rCategory: 'approved',
    stlaXpStatus: 'STLA Approved: 16 Jul 2024 - 15 Jul 2025', stlaCategory: 'approved',
    accessPermission: 'Obtained by RSS', accessCategory: 'approved',
    engineeringPlan: 'No comment from MR', engineeringPlanCategory: 'approved',
    tprpTwvp: 'Approved by TWVP 4 Sep 2024', tprpTwvpCategory: 'approved',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'HSSP endorsed', hsspCategory: 'approved',
    coordinates: { lat: 22.3945, lng: 113.9745 },
    accepted: false,
  },
  // === Row 2 ===
  {
    id: '2', no: 2, agreement: 'CE 47/2022 (GE)',
    location: "West of Tin's Centre Block 9, Hung Cheung Road, Tuen Mun",
    featureNo: '5SE-B/R53',
    s3rStatus: 'S3R Accepted by GEO on 1 Aug 2024', s3rCategory: 'approved',
    stlaXpStatus: 'STLA Approved: 16 Jul 2024 - 15 Jul 2025', stlaCategory: 'approved',
    accessPermission: 'Obtained by RSS', accessCategory: 'approved',
    engineeringPlan: 'No comment memo dated 12 Sep 2024', engineeringPlanCategory: 'approved',
    tprpTwvp: 'N/A (no trees)', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.3952, lng: 113.9738 },
    accepted: false,
  },
  // === Row 3 ===
  {
    id: '3', no: 3, agreement: 'CE 47/2022 (GE)',
    location: 'Sham Tseng East Village Sitting-out Area, Tsuen Wan',
    featureNo: '6SE-C/CR354',
    s3rStatus: 'S3R Accepted by GEO on 31 July 2024', s3rCategory: 'approved',
    stlaXpStatus: 'STLA Approved: 1 Oct 2024 - 30 Sep 2025', stlaCategory: 'approved',
    accessPermission: 'N/A', accessCategory: 'not-applicable',
    engineeringPlan: 'No comment from MR', engineeringPlanCategory: 'approved',
    tprpTwvp: 'Approved by TWVP', tprpTwvpCategory: 'approved',
    tprpMr: 'Approved by MR', tprpMrCategory: 'approved',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.3685, lng: 114.0582 },
    accepted: false,
  },
  // === Row 4 ===
  {
    id: '4', no: 4, agreement: 'CE 47/2022 (GE)',
    location: 'East of Peak Castle, Siu Lam, Tuen Mun',
    featureNo: '6SW-D/C306',
    s3rStatus: 'Revised S3R submitted on 29 Oct 2024', s3rCategory: 'submitted',
    stlaXpStatus: 'To be applied after obtaining consent', stlaCategory: 'pending',
    accessPermission: 'Seeking consent. 1st Reminder 22 Jan 2025', accessCategory: 'pending',
    engineeringPlan: 'No comment from MR', engineeringPlanCategory: 'approved',
    tprpTwvp: 'Pending comment from LandsD', tprpTwvpCategory: 'pending',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.3628, lng: 114.0125 },
    accepted: false,
  },
  // === Row 5 ===
  {
    id: '5', no: 5, agreement: 'CE 47/2022 (GE)',
    location: 'South of Lot No. 217 in D.D. 218, Siu Lam, Tuen Mun',
    featureNo: '6SW-D/C304',
    s3rStatus: 'Revised S3R submitted on 29 Oct 2024', s3rCategory: 'submitted',
    stlaXpStatus: 'To be applied after obtaining consent', stlaCategory: 'pending',
    accessPermission: 'Seeking consent. 1st Reminder 22 Jan 2025', accessCategory: 'pending',
    engineeringPlan: 'No comment from MR', engineeringPlanCategory: 'approved',
    tprpTwvp: 'Pending comment from LandsD', tprpTwvpCategory: 'pending',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.3620, lng: 114.0130 },
    accepted: false,
  },
  // === Row 6 ===
  {
    id: '6', no: 6, agreement: 'CE 47/2022 (GE)',
    location: 'East of Lot No. 206 in D.D. 218, Siu Lam, Tuen Mun',
    featureNo: '6SW-D/C299',
    s3rStatus: 'Revised S3R submitted on 29 Oct 2024', s3rCategory: 'submitted',
    stlaXpStatus: 'To be applied after obtaining consent', stlaCategory: 'pending',
    accessPermission: 'Seeking consent. 1st Reminder 22 Jan 2025', accessCategory: 'pending',
    engineeringPlan: 'No comment from MR', engineeringPlanCategory: 'approved',
    tprpTwvp: 'Pending comment from LandsD', tprpTwvpCategory: 'pending',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.3615, lng: 114.0135 },
    accepted: false,
  },
  // === Row 7 ===
  {
    id: '7', no: 7, agreement: 'CE 47/2022 (GE)',
    location: 'West of Ting Kau Village, Tsuen Wan',
    featureNo: '6SE-C/C648',
    s3rStatus: 'S3R under preparation', s3rCategory: 'draft',
    stlaXpStatus: 'To be applied', stlaCategory: 'pending',
    accessPermission: 'N/A', accessCategory: 'not-applicable',
    engineeringPlan: 'To be submitted', engineeringPlanCategory: 'pending',
    tprpTwvp: 'Tree survey Batch 2', tprpTwvpCategory: 'pending',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'To be submitted', hsspCategory: 'pending',
    coordinates: { lat: 22.3750, lng: 114.0550 },
    accepted: false,
  },
  // === Row 8 ===
  {
    id: '8', no: 8, agreement: 'CE 47/2022 (GE)',
    location: 'Northwest of Sham Tseng Raw Water Pumping Station',
    featureNo: '6SE-C/CR310',
    s3rStatus: 'Final S3R submitted 10 Sep 2025. RTC (pending drawings)', s3rCategory: 'submitted',
    stlaXpStatus: 'N/A (GLA)', stlaCategory: 'not-applicable',
    accessPermission: 'Pending confirmation with WSD', accessCategory: 'pending',
    engineeringPlan: 'Submitted 2 Oct 2025', engineeringPlanCategory: 'submitted',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.3695, lng: 114.0550 },
    accepted: false,
  },
  // === Row 9 ===
  {
    id: '9', no: 9, agreement: 'CE 47/2022 (GE)',
    location: 'Po Kat Tsai Village, Sha Tau Kok',
    featureNo: '3SW-B/C335',
    s3rStatus: 'Final S3R accepted on 10 Oct 2025', s3rCategory: 'approved',
    stlaXpStatus: 'Submitted on 21 Oct 2025', stlaCategory: 'submitted',
    accessPermission: 'Consent obtained (Ms. Wu) 23 Oct 2025', accessCategory: 'approved',
    engineeringPlan: 'Submitted 28 Nov 2025', engineeringPlanCategory: 'submitted',
    tprpTwvp: 'Submitted 28 Nov 2025', tprpTwvpCategory: 'submitted',
    tprpMr: 'Submitted 28 Nov 2025', tprpMrCategory: 'submitted',
    hsspStatus: 'Submitted 21 Nov 2025', hsspCategory: 'submitted',
    coordinates: { lat: 22.5430, lng: 114.2185 },
    accepted: false,
  },
  // === Row 10 ===
  {
    id: '10', no: 10, agreement: 'CE 47/2022 (GE)',
    location: 'South of House No. 40B, Siu Sau Village, Tuen Mun',
    featureNo: '6SW-C/C799',
    s3rStatus: 'S3R to be submitted Oct 2025', s3rCategory: 'pending',
    stlaXpStatus: 'ARE - draft memo', stlaCategory: 'draft',
    accessPermission: 'Consent obtained from Mr. Chu', accessCategory: 'approved',
    engineeringPlan: 'To be submitted', engineeringPlanCategory: 'pending',
    tprpTwvp: 'Tree survey Batch 2', tprpTwvpCategory: 'pending',
    tprpMr: 'To be submitted', tprpMrCategory: 'pending',
    hsspStatus: 'To be submitted', hsspCategory: 'pending',
    coordinates: { lat: 22.3710, lng: 114.0020 },
    accepted: false,
  },
  // === Row 11 ===
  {
    id: '11', no: 11, agreement: 'CE 47/2022 (GE)',
    location: 'Northwest of Deauville, Tuen Mun Road',
    featureNo: '6SE-C/C675',
    s3rStatus: 'Comments received 10 Sep 2025. Resubmit by 10 Dec 2025', s3rCategory: 'rejected',
    stlaXpStatus: 'XP application to be submitted', stlaCategory: 'pending',
    accessPermission: 'N/A', accessCategory: 'not-applicable',
    engineeringPlan: 'Submitted 26 June 2025', engineeringPlanCategory: 'submitted',
    tprpTwvp: 'Comments received 21 Nov 2025', tprpTwvpCategory: 'rejected',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.3755, lng: 114.0050 },
    accepted: false,
  },
  // === Row 12 ===
  {
    id: '12', no: 12, agreement: 'CE 47/2022 (GE)',
    location: 'North of Tong Fuk, Lantau Island Catchwater Section F',
    featureNo: '13NE-A/CR177',
    s3rStatus: 'Final S3R accepted 12 May 2025', s3rCategory: 'approved',
    stlaXpStatus: 'STLA-TIS 236 (Jun 2025 - May 2026)', stlaCategory: 'approved',
    accessPermission: 'Liaison with AFCD underway', accessCategory: 'pending',
    engineeringPlan: 'Received 10 Nov 2025', engineeringPlanCategory: 'approved',
    tprpTwvp: 'Comments received 26 June 2025', tprpTwvpCategory: 'rejected',
    tprpMr: 'To be submitted', tprpMrCategory: 'pending',
    hsspStatus: 'Approved on 7 Oct 2025', hsspCategory: 'approved',
    coordinates: { lat: 22.2350, lng: 113.9350 },
    accepted: false,
  },
  // === Row 13 ===
  {
    id: '13', no: 13, agreement: 'CE 47/2022 (GE)',
    location: 'South of Tong Fuk Village, Catchwater Section G, Lantau Island',
    featureNo: '13NE-A/CR165',
    s3rStatus: 'Final S3R accepted 15 May 2025', s3rCategory: 'approved',
    stlaXpStatus: 'STLA-TIS 237 (Jun 2025 - May 2026)', stlaCategory: 'approved',
    accessPermission: 'Liaison with AFCD underway', accessCategory: 'pending',
    engineeringPlan: 'Submitted 10 Nov 2025', engineeringPlanCategory: 'submitted',
    tprpTwvp: 'Submitted 2 July 2025', tprpTwvpCategory: 'submitted',
    tprpMr: 'To be submitted', tprpMrCategory: 'pending',
    hsspStatus: 'Approved on 7 Oct 2025', hsspCategory: 'approved',
    coordinates: { lat: 22.2340, lng: 113.9340 },
    accepted: false,
  },
  // === Row 14 ===
  {
    id: '14', no: 14, agreement: 'CE 47/2022 (GE)',
    location: 'East of Tai Lam Tunnel Toll Plaza, Tuen Mun',
    featureNo: '6NE-D/C52',
    s3rStatus: 'S3R under preparation', s3rCategory: 'draft',
    stlaXpStatus: 'N/A (GL)', stlaCategory: 'not-applicable',
    accessPermission: 'N/A (GL)', accessCategory: 'not-applicable',
    engineeringPlan: 'To be submitted', engineeringPlanCategory: 'pending',
    tprpTwvp: 'Tree survey Batch 2', tprpTwvpCategory: 'pending',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'To be submitted', hsspCategory: 'pending',
    coordinates: { lat: 22.3780, lng: 114.0400 },
    accepted: false,
  },
  // === Row 15 ===
  {
    id: '15', no: 15, agreement: 'CE 47/2022 (GE)',
    location: 'Northeast of Sea Crest Villa, Castle Peak Road, Tuen Mun',
    featureNo: '6SE-C/CR312',
    s3rStatus: 'Final S3R submitted 20 Sep 2025', s3rCategory: 'submitted',
    stlaXpStatus: 'STLA applied 15 Oct 2025', stlaCategory: 'submitted',
    accessPermission: 'Verbal consent obtained', accessCategory: 'approved',
    engineeringPlan: 'To be submitted', engineeringPlanCategory: 'pending',
    tprpTwvp: 'To be submitted', tprpTwvpCategory: 'pending',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'To be submitted', hsspCategory: 'pending',
    coordinates: { lat: 22.3730, lng: 114.0480 },
    accepted: false,
  },
  // === Row 16 ===
  {
    id: '16', no: 16, agreement: 'CE 47/2022 (GE)',
    location: 'Southwest of Coral Beach, Castle Peak Road, Tuen Mun',
    featureNo: '6SE-C/C680',
    s3rStatus: 'S3R under preparation', s3rCategory: 'draft',
    stlaXpStatus: 'To be applied', stlaCategory: 'pending',
    accessPermission: 'Seeking consent', accessCategory: 'pending',
    engineeringPlan: 'To be submitted', engineeringPlanCategory: 'pending',
    tprpTwvp: 'Tree survey Batch 3', tprpTwvpCategory: 'pending',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'To be submitted', hsspCategory: 'pending',
    coordinates: { lat: 22.3720, lng: 114.0510 },
    accepted: false,
  },
  // === Row 17 ===
  {
    id: '17', no: 17, agreement: 'CE 47/2022 (GE)',
    location: 'East of Hong Kong Gold Coast, Castle Peak Road',
    featureNo: '6SE-C/C678',
    s3rStatus: 'S3R under preparation', s3rCategory: 'draft',
    stlaXpStatus: 'To be applied', stlaCategory: 'pending',
    accessPermission: 'Seeking consent from owner', accessCategory: 'pending',
    engineeringPlan: 'To be submitted', engineeringPlanCategory: 'pending',
    tprpTwvp: 'Tree survey Batch 2', tprpTwvpCategory: 'pending',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'To be confirmed with VR', hsspCategory: 'pending',
    coordinates: { lat: 22.3740, lng: 114.0480 },
    accepted: false,
  },
  // === Row 18 ===
  {
    id: '18', no: 18, agreement: 'CE 47/2022 (GE)',
    location: 'North of Sham Tseng Village',
    featureNo: '6SE-C/F92',
    s3rStatus: 'S3R under preparation', s3rCategory: 'draft',
    stlaXpStatus: 'STLA for GI terminated', stlaCategory: 'rejected',
    accessPermission: 'Verbal consent obtained', accessCategory: 'approved',
    engineeringPlan: 'To be submitted', engineeringPlanCategory: 'pending',
    tprpTwvp: 'Tree survey Batch 2', tprpTwvpCategory: 'pending',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'To be confirmed with VR', hsspCategory: 'pending',
    coordinates: { lat: 22.3680, lng: 114.0590 },
    accepted: false,
  },
  // === Row 19 ===
  {
    id: '19', no: 19, agreement: 'CE 47/2022 (GE)',
    location: 'South of Sham Tseng San Tsuen, Tsuen Wan',
    featureNo: '6SE-C/F95',
    s3rStatus: 'Option report under preparation', s3rCategory: 'draft',
    stlaXpStatus: 'To be applied after S3R', stlaCategory: 'pending',
    accessPermission: 'Consent obtained from village representative', accessCategory: 'approved',
    engineeringPlan: 'To be submitted', engineeringPlanCategory: 'pending',
    tprpTwvp: 'Tree survey Batch 3', tprpTwvpCategory: 'pending',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'To be submitted', hsspCategory: 'pending',
    coordinates: { lat: 22.3670, lng: 114.0600 },
    accepted: false,
  },
  // === Row 20 ===
  {
    id: '20', no: 20, agreement: 'CE 47/2022 (GE)',
    location: 'Northeast of Hong Kong Garden, Sham Tseng',
    featureNo: '6SE-C/CR360',
    s3rStatus: 'S3R under preparation', s3rCategory: 'draft',
    stlaXpStatus: 'To be applied', stlaCategory: 'pending',
    accessPermission: 'N/A', accessCategory: 'not-applicable',
    engineeringPlan: 'To be submitted', engineeringPlanCategory: 'pending',
    tprpTwvp: 'To be submitted', tprpTwvpCategory: 'pending',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.3675, lng: 114.0610 },
    accepted: false,
  },
  // === Row 21 ===
  {
    id: '21', no: 21, agreement: 'CE 47/2022 (GE)',
    location: 'West of Lido Beach, Castle Peak Road',
    featureNo: '6SE-C/C690',
    s3rStatus: 'Option report submitted 10 Oct 2025', s3rCategory: 'submitted',
    stlaXpStatus: 'To be applied after S3R', stlaCategory: 'pending',
    accessPermission: 'Pending', accessCategory: 'pending',
    engineeringPlan: 'To be submitted', engineeringPlanCategory: 'pending',
    tprpTwvp: 'To be submitted', tprpTwvpCategory: 'pending',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'To be submitted', hsspCategory: 'pending',
    coordinates: { lat: 22.3665, lng: 114.0700 },
    accepted: false,
  },
  // === Row 22 ===
  {
    id: '22', no: 22, agreement: 'CE 47/2022 (GE)',
    location: 'North of Lido Beach, Tsing Long Highway',
    featureNo: '6SE-C/FR228',
    s3rStatus: 'Option report accepted 22 May 2025', s3rCategory: 'approved',
    stlaXpStatus: 'GI commenced Dec 2025', stlaCategory: 'pending',
    accessPermission: 'Pending', accessCategory: 'pending',
    engineeringPlan: 'To be submitted', engineeringPlanCategory: 'pending',
    tprpTwvp: 'To be submitted', tprpTwvpCategory: 'pending',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'To be submitted', hsspCategory: 'pending',
    coordinates: { lat: 22.3660, lng: 114.0720 },
    accepted: false,
  },
  // === Row 23 ===
  {
    id: '23', no: 23, agreement: 'CE 47/2022 (GE)',
    location: 'East of Kadoorie Beach, Castle Peak Road',
    featureNo: '6SE-D/C442',
    s3rStatus: 'S3R under preparation', s3rCategory: 'draft',
    stlaXpStatus: 'To be applied', stlaCategory: 'pending',
    accessPermission: 'N/A', accessCategory: 'not-applicable',
    engineeringPlan: 'To be submitted', engineeringPlanCategory: 'pending',
    tprpTwvp: 'To be submitted', tprpTwvpCategory: 'pending',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.3700, lng: 114.0680 },
    accepted: false,
  },
  // === Row 24 ===
  {
    id: '24', no: 24, agreement: 'CE 47/2022 (GE)',
    location: 'North of Lung Yeuk Tau, Fanling',
    featureNo: '3NE-D/C180',
    s3rStatus: 'Option report under preparation', s3rCategory: 'draft',
    stlaXpStatus: 'To be applied', stlaCategory: 'pending',
    accessPermission: 'To be obtained', accessCategory: 'pending',
    engineeringPlan: 'To be submitted', engineeringPlanCategory: 'pending',
    tprpTwvp: 'To be submitted', tprpTwvpCategory: 'pending',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'To be submitted', hsspCategory: 'pending',
    coordinates: { lat: 22.5050, lng: 114.1450 },
    accepted: false,
  },
  // === Row 25 ===
  {
    id: '25', no: 25, agreement: 'CE 47/2022 (GE)',
    location: 'West of Ta Kwu Ling, North District',
    featureNo: '3SW-B/C340',
    s3rStatus: 'Option report under preparation', s3rCategory: 'draft',
    stlaXpStatus: 'To be applied', stlaCategory: 'pending',
    accessPermission: 'To be obtained', accessCategory: 'pending',
    engineeringPlan: 'To be submitted', engineeringPlanCategory: 'pending',
    tprpTwvp: 'To be submitted', tprpTwvpCategory: 'pending',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'To be submitted', hsspCategory: 'pending',
    coordinates: { lat: 22.5300, lng: 114.1600 },
    accepted: false,
  },
  // === Row 26 ===
  {
    id: '26', no: 26, agreement: 'CE 47/2022 (GE)',
    location: 'South of Discovery Bay, Lantau Island',
    featureNo: '11SE-A/C115',
    s3rStatus: 'Option report under preparation', s3rCategory: 'draft',
    stlaXpStatus: 'To be applied', stlaCategory: 'pending',
    accessPermission: 'To be obtained', accessCategory: 'pending',
    engineeringPlan: 'To be submitted', engineeringPlanCategory: 'pending',
    tprpTwvp: 'To be submitted', tprpTwvpCategory: 'pending',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'To be submitted', hsspCategory: 'pending',
    coordinates: { lat: 22.2900, lng: 114.0150 },
    accepted: false,
  },
  // === Row 27 ===
  {
    id: '27', no: 27, agreement: 'CE 47/2022 (GE)',
    location: 'North of Tsing Yi Bridge, Tsuen Wan',
    featureNo: '6NE-A/C420',
    s3rStatus: 'GI commenced Nov 2025', s3rCategory: 'draft',
    stlaXpStatus: 'To be applied', stlaCategory: 'pending',
    accessPermission: 'N/A', accessCategory: 'not-applicable',
    engineeringPlan: 'To be submitted', engineeringPlanCategory: 'pending',
    tprpTwvp: 'To be submitted', tprpTwvpCategory: 'pending',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'To be submitted', hsspCategory: 'pending',
    coordinates: { lat: 22.3550, lng: 114.1050 },
    accepted: false,
  },

  // =========================================
  // CE 53/2022 (GE) - Hong Kong Island
  // =========================================

  // === CE53 Row 1 ===
  {
    id: 'ce53-1', no: 1, agreement: 'CE 53/2022 (GE)',
    location: 'South of Pok Fu Lam Salt Water Service Reservoir',
    featureNo: '11SW-C/C406',
    s3rStatus: 'Option accepted 9 Aug 2024; S3R accepted 2 May 2025', s3rCategory: 'approved',
    stlaXpStatus: 'STLA-THKWS 161 (16 Jul 2025 – 30 Apr 2026)', stlaCategory: 'approved',
    accessPermission: 'Approved on 30 May 2025; No comment from MR 7 Apr 2025', accessCategory: 'approved',
    engineeringPlan: 'Submitted on 13 May 2025; No Comments 7 Nov 2025', engineeringPlanCategory: 'approved',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2600, lng: 114.1300 },
    accepted: false,
  },
  // === CE53 Row 2 ===
  {
    id: 'ce53-2', no: 2, agreement: 'CE 53/2022 (GE)',
    location: 'East of Hong Kong Museum of Coastal Defence',
    featureNo: '11SE-B/CR563',
    s3rStatus: 'Option accepted 9 Sep 2025; S3R accepted 2 Oct 2025', s3rCategory: 'approved',
    stlaXpStatus: 'N/A', stlaCategory: 'not-applicable',
    accessPermission: 'Site Visit LCSD Sep 2025; LCSD no comments 20 Oct 2025', accessCategory: 'approved',
    engineeringPlan: 'Approved 10 Oct 2025; No Comments 2 Oct 2025', engineeringPlanCategory: 'approved',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2840, lng: 114.2340 },
    accepted: false,
  },
  // === CE53 Row 3 ===
  {
    id: 'ce53-3', no: 3, agreement: 'CE 53/2022 (GE)',
    location: 'Northeast of Ap Lei Chau No. 2 Fresh Water Service Reservoir',
    featureNo: '15NW-A/C112',
    s3rStatus: 'Option accepted 7 Nov 2024; Final S3R submitted 7 Nov 2025', s3rCategory: 'submitted',
    stlaXpStatus: 'N/A', stlaCategory: 'not-applicable',
    accessPermission: 'WSD has no comments 31 Oct 2025', accessCategory: 'approved',
    engineeringPlan: 'No comments from WSD MW, WSD SS & MTR 23 Sep 2025', engineeringPlanCategory: 'approved',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2480, lng: 114.1520 },
    accepted: false,
  },
  // === CE53 Row 4 ===
  {
    id: 'ce53-4', no: 4, agreement: 'CE 53/2022 (GE)',
    location: 'Southwest of Kwun Yam Temple, Ap Lei Chau Main Street',
    featureNo: '15NW-B/C139',
    s3rStatus: 'Option report accepted 7 Nov 2024; S3R accepted 31 Oct 2025', s3rCategory: 'approved',
    stlaXpStatus: 'N/A', stlaCategory: 'not-applicable',
    accessPermission: 'LCSD has no comments 25 Nov 2025', accessCategory: 'approved',
    engineeringPlan: 'Approved 2 Sep 2025; No Comments 3 Nov 2025', engineeringPlanCategory: 'approved',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2400, lng: 114.1480 },
    accepted: false,
  },
  // === CE53 Row 5 ===
  {
    id: 'ce53-5', no: 5, agreement: 'CE 53/2022 (GE)',
    location: 'Southwest of Kwun Yam Temple, Ap Lei Chau Main Street',
    featureNo: '15NW-B/C263',
    s3rStatus: 'Option report accepted 7 Nov 2024; S3R accepted 11 Nov 2025', s3rCategory: 'approved',
    stlaXpStatus: 'N/A', stlaCategory: 'not-applicable',
    accessPermission: 'LCSD & ArchSD no comments Jul-Nov 2025', accessCategory: 'approved',
    engineeringPlan: 'Approved with Condition 2 Sep 2025; MR no comment 22 Jul 2025', engineeringPlanCategory: 'approved',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2410, lng: 114.1470 },
    accepted: false,
  },
  // === CE53 Row 6 ===
  {
    id: 'ce53-6', no: 6, agreement: 'CE 53/2022 (GE)',
    location: 'Southeast of Aviary, Hong Kong Park, Kennedy Road',
    featureNo: '11SW-B/R415',
    s3rStatus: 'Option accepted 21 Dec 2023; S3R accepted 27 Dec 2024', s3rCategory: 'approved',
    stlaXpStatus: 'N/A', stlaCategory: 'not-applicable',
    accessPermission: 'Permission by LCSD in Mar 2026; MR no comment 25 Dec 2024', accessCategory: 'pending',
    engineeringPlan: 'Approved 6 Feb 2025; MR no comment 25 Dec 2024', engineeringPlanCategory: 'approved',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2780, lng: 114.1620 },
    accepted: false,
  },
  // === CE53 Row 7 ===
  {
    id: 'ce53-7', no: 7, agreement: 'CE 53/2022 (GE)',
    location: 'South of Lin Fa Kung Garden, Lai Tak Tsuen Road',
    featureNo: '11SE-A/C930',
    s3rStatus: 'Option accepted 8 Aug 2024; Revised S3R submitted 11 Feb 2026', s3rCategory: 'submitted',
    stlaXpStatus: 'XP Application is in progress', stlaCategory: 'pending',
    accessPermission: 'ArchSD and HyD Slope no comments Jun/Oct 2025', accessCategory: 'approved',
    engineeringPlan: 'To be submitted; HyD Landscape comments received 20 Nov 2025', engineeringPlanCategory: 'pending',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2780, lng: 114.1920 },
    accepted: false,
  },
  // === CE53 Row 8 ===
  {
    id: 'ce53-8', no: 8, agreement: 'CE 53/2022 (GE)',
    location: 'Northeast of Peak Police Station, Peak Road',
    featureNo: '11SW-D/CR1618',
    s3rStatus: 'Option accepted 6 Jun 2024; S3R accepted 9 Jan 2026', s3rCategory: 'approved',
    stlaXpStatus: 'STLA memo replied 2 Mar 2026', stlaCategory: 'submitted',
    accessPermission: 'Liaison with HKPF underway; MR no comment 25 Dec 2024', accessCategory: 'pending',
    engineeringPlan: 'Submitted 9 Feb 2026; No Comments 4 Feb 2026', engineeringPlanCategory: 'submitted',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2720, lng: 114.1500 },
    accepted: false,
  },
  // === CE53 Row 9 ===
  {
    id: 'ce53-9', no: 9, agreement: 'CE 53/2022 (GE)',
    location: 'North of the Summit, Bowen Road, Happy Valley',
    featureNo: '11SW-D/R376*',
    s3rStatus: 'Option accepted 16 Jul 2024; S3R accepted 15 Jan 2025', s3rCategory: 'approved',
    stlaXpStatus: 'STLA-THKE 89; XP: Feb 2026-Oct 2026', stlaCategory: 'approved',
    accessPermission: 'N/A', accessCategory: 'not-applicable',
    engineeringPlan: 'MR: No comment 2 May 2025; CEDD/LD: Approved with Cond 28 Nov 2024', engineeringPlanCategory: 'approved',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2740, lng: 114.1800 },
    accepted: false,
  },
  // === CE53 Row 10 ===
  {
    id: 'ce53-10', no: 10, agreement: 'CE 53/2022 (GE)',
    location: 'Northeast of Evergreen Villa, Bowen Road, Happy Valley',
    featureNo: '11SW-D/R619*',
    s3rStatus: 'Option accepted 20 Dec 2023; S3R accepted 6 Oct 2025', s3rCategory: 'approved',
    stlaXpStatus: 'STLA-THKE 90; XP: Feb 2026-Nov 2026', stlaCategory: 'approved',
    accessPermission: 'N/A', accessCategory: 'not-applicable',
    engineeringPlan: 'MR: No comment 22 May 2025; CEDD/LD: Approved with Cond 28 Nov 2024', engineeringPlanCategory: 'approved',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2750, lng: 114.1820 },
    accepted: false,
  },
  // === CE53 Row 11 ===
  {
    id: 'ce53-11', no: 11, agreement: 'CE 53/2022 (GE)',
    location: 'Southeast of House No. 35-41, Village Terrace, Happy Valley',
    featureNo: '11SW-D/C2279',
    s3rStatus: 'Option accepted 6 Jun 2024; S3R accepted 14 Jan 2025', s3rCategory: 'approved',
    stlaXpStatus: 'STLA-THKE 92; XP: Feb 2026-Nov 2026', stlaCategory: 'approved',
    accessPermission: 'N/A', accessCategory: 'not-applicable',
    engineeringPlan: 'MR: No comment 6 Dec 2024; CEDD/LD: Approved with Cond 28 Nov 2024', engineeringPlanCategory: 'approved',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2700, lng: 114.1850 },
    accepted: false,
  },
  // === CE53 Row 12 ===
  {
    id: 'ce53-12', no: 12, agreement: 'CE 53/2022 (GE)',
    location: 'Southeast of House No. 35-41, Village Terrace, Happy Valley',
    featureNo: '11SW-D/C2327',
    s3rStatus: 'Option accepted 8 Jul 2024; S3R accepted 14 Jan 2025', s3rCategory: 'approved',
    stlaXpStatus: 'STLA-THKE 91; XP: Feb 2026-Dec 2026', stlaCategory: 'approved',
    accessPermission: 'N/A', accessCategory: 'not-applicable',
    engineeringPlan: 'MR: No comment 18 Dec 2024; CEDD/LD: Approved with Cond 28 Nov 2024', engineeringPlanCategory: 'approved',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2690, lng: 114.1860 },
    accepted: false,
  },
  // === CE53 Row 13 ===
  {
    id: 'ce53-13', no: 13, agreement: 'CE 53/2022 (GE)',
    location: 'West of House No. 8-16, Wing Wah Lane',
    featureNo: '11SW-B/R735',
    s3rStatus: 'Option accepted 24 Sep 2024; S3R accepted 6 Jan 2026', s3rCategory: 'approved',
    stlaXpStatus: 'XP Application is in progress', stlaCategory: 'pending',
    accessPermission: 'N/A', accessCategory: 'not-applicable',
    engineeringPlan: 'MR: No comments Nov/Dec 2025; CEDD/LD: Submitted 5 Jan 2026', engineeringPlanCategory: 'submitted',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2820, lng: 114.1540 },
    accepted: false,
  },
  // === CE53 Row 14 ===
  {
    id: 'ce53-14', no: 14, agreement: 'CE 53/2022 (GE)',
    location: 'West of House No. 18, Stanley Village Road, Stanley',
    featureNo: '15NE-A/C762',
    s3rStatus: 'Option accepted 4 Dec 2024; S3R accepted 31 Dec 2025', s3rCategory: 'approved',
    stlaXpStatus: 'XP Application is in progress', stlaCategory: 'pending',
    accessPermission: 'N/A', accessCategory: 'not-applicable',
    engineeringPlan: 'HyD: No comments Aug 2025/Feb 2026; CEDD/LD: Submitted 26 Feb 2026', engineeringPlanCategory: 'submitted',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2180, lng: 114.2130 },
    accepted: false,
  },
  // === CE53 Row 15 ===
  {
    id: 'ce53-15', no: 15, agreement: 'CE 53/2022 (GE)',
    location: 'North of House No. 51A-51H, Mount Kellett Road, the Peak',
    featureNo: '11SW-C/C672',
    s3rStatus: 'Option accepted 27 Sep 2024; S3R accepted 25 Feb 2026', s3rCategory: 'approved',
    stlaXpStatus: 'STLA App to DLO 9 Mar 2026; XP App in progress', stlaCategory: 'submitted',
    accessPermission: 'N/A', accessCategory: 'not-applicable',
    engineeringPlan: 'HyD/LandsD: No comments Feb/Mar 2026; CEDD/LD: Submitted 10 Feb 2026', engineeringPlanCategory: 'submitted',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2600, lng: 114.1480 },
    accepted: false,
  },
  // === CE53 Row 16 ===
  {
    id: 'ce53-16', no: 16, agreement: 'CE 53/2022 (GE)',
    location: 'South of Aviary, Hong Kong Park, Kennedy Road, Admiralty',
    featureNo: '11SW-B/FR146*',
    s3rStatus: 'Option accepted 14 Nov 2025; Revised S3R submitted 9 Mar 2026', s3rCategory: 'submitted',
    stlaXpStatus: 'N/A', stlaCategory: 'not-applicable',
    accessPermission: 'To be submitted in due course', accessCategory: 'pending',
    engineeringPlan: 'ArchSD comments received 14 Oct 2025; Revision sub to GEO/MR Mar 2026', engineeringPlanCategory: 'pending',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2770, lng: 114.1610 },
    accepted: false,
  },
  // === CE53 Row 17 ===
  {
    id: 'ce53-17', no: 17, agreement: 'CE 53/2022 (GE)',
    location: 'South of Aviary, Hong Kong Park, Kennedy Road, Admiralty',
    featureNo: '11SW-B/FR157*',
    s3rStatus: 'Comments on Option 4 Nov 2025; Revised Option submitted 10 Feb 2026', s3rCategory: 'pending',
    stlaXpStatus: 'N/A', stlaCategory: 'not-applicable',
    accessPermission: 'To be submitted in due course', accessCategory: 'pending',
    engineeringPlan: 'To be submitted in due course', engineeringPlanCategory: 'pending',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2760, lng: 114.1600 },
    accepted: false,
  },
  // === CE53 Row 18 ===
  {
    id: 'ce53-18', no: 18, agreement: 'CE 53/2022 (GE)',
    location: 'Southwest of Pok Fu Lam Transit Nursery, 150 Pok Fu Lam Road',
    featureNo: '11SW-C/FR78',
    s3rStatus: 'Option accepted 8 Jan 2026; Draft S3R submitted 13 Feb 2026', s3rCategory: 'submitted',
    stlaXpStatus: 'N/A', stlaCategory: 'not-applicable',
    accessPermission: 'To be submitted in due course', accessCategory: 'pending',
    engineeringPlan: 'Submitted 13 Feb 2026; CEDD/LD: To be sub in due course', engineeringPlanCategory: 'submitted',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2620, lng: 114.1280 },
    accepted: false,
  },
  // === CE53 Row 19 ===
  {
    id: 'ce53-19', no: 19, agreement: 'CE 53/2022 (GE)',
    location: 'North of Emerald Garden, Pok Fu Lam Road, Pok Fu Lam',
    featureNo: '11SW-A/C1240',
    s3rStatus: 'Option accepted 24 Dec 2025; Draft S3R sub within Mar 2026', s3rCategory: 'submitted',
    stlaXpStatus: 'N/A', stlaCategory: 'not-applicable',
    accessPermission: 'To be submitted in due course', accessCategory: 'pending',
    engineeringPlan: 'To be submitted within Mar 2026; CEDD/LD: To be sub in due course', engineeringPlanCategory: 'pending',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2700, lng: 114.1350 },
    accepted: false,
  },
  // === CE53 Row 20 ===
  {
    id: 'ce53-20', no: 20, agreement: 'CE 53/2022 (GE)',
    location: 'Southwest of Suncliffe Place, 7 Comfort Terrace, North Point',
    featureNo: '11SE-A/F187',
    s3rStatus: 'Option accepted 9 Dec 2025; Draft S3R under preparation', s3rCategory: 'draft',
    stlaXpStatus: 'N/A', stlaCategory: 'not-applicable',
    accessPermission: 'To be submitted in due course', accessCategory: 'pending',
    engineeringPlan: 'To be submitted in due course', engineeringPlanCategory: 'pending',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2890, lng: 114.1980 },
    accepted: false,
  },
  // === CE53 Row 21 ===
  {
    id: 'ce53-21', no: 21, agreement: 'CE 53/2022 (GE)',
    location: 'Southwest of Fortress Hill Playground, Fortress Hill Road, North Point',
    featureNo: '11SE-A/F216',
    s3rStatus: 'Option accepted 31 Dec 2025; S3R to be sub in due course', s3rCategory: 'pending',
    stlaXpStatus: 'N/A', stlaCategory: 'not-applicable',
    accessPermission: 'To be submitted in due course', accessCategory: 'pending',
    engineeringPlan: 'To be submitted in due course', engineeringPlanCategory: 'pending',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2890, lng: 114.1940 },
    accepted: false,
  },
  // === CE53 Row 22 ===
  {
    id: 'ce53-22', no: 22, agreement: 'CE 53/2022 (GE)',
    location: 'West of Hong Kong Tennis Centre, House No. 133, Wong Nai Chung Gap Road, Tai Tam',
    featureNo: '11SE-C/FR25',
    s3rStatus: 'Option accepted 14 Nov 2024; S3R to be sub in due course', s3rCategory: 'pending',
    stlaXpStatus: 'N/A', stlaCategory: 'not-applicable',
    accessPermission: 'To be submitted in due course', accessCategory: 'pending',
    engineeringPlan: 'To be submitted in due course', engineeringPlanCategory: 'pending',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2610, lng: 114.1900 },
    accepted: false,
  },
  // === CE53 Row 23 ===
  {
    id: 'ce53-23', no: 23, agreement: 'CE 53/2022 (GE)',
    location: 'West of House No. 13-17, Wing Wah Lane, Central',
    featureNo: '11SW-B/FR242',
    s3rStatus: 'Comments on Option 28 Nov 2025; Revised Option submitted 13 Feb 2026', s3rCategory: 'pending',
    stlaXpStatus: 'N/A', stlaCategory: 'not-applicable',
    accessPermission: 'To be submitted in due course', accessCategory: 'pending',
    engineeringPlan: 'To be submitted in due course', engineeringPlanCategory: 'pending',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2830, lng: 114.1530 },
    accepted: false,
  },
  // === CE53 Row 24 ===
  {
    id: 'ce53-24', no: 24, agreement: 'CE 53/2022 (GE)',
    location: 'Pok Fu Lam Nursery, Pok Fu Lam, Hong Kong',
    featureNo: '11SW-C/FR41',
    s3rStatus: 'Option accepted 3 Mar 2026; S3R to be sub in due course', s3rCategory: 'pending',
    stlaXpStatus: 'N/A', stlaCategory: 'not-applicable',
    accessPermission: 'To be submitted in due course', accessCategory: 'pending',
    engineeringPlan: 'CEDD/LD: Approved 7 Mar 2025; MR/TPRP to be sub in due course', engineeringPlanCategory: 'approved',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2610, lng: 114.1310 },
    accepted: false,
  },
  // === CE53 Row 25 ===
  {
    id: 'ce53-25', no: 25, agreement: 'CE 53/2022 (GE)',
    location: 'North of Evergreen Villa, Bowen Road, Happy Valley',
    featureNo: '11SW-D/R608',
    s3rStatus: 'Option accepted 6 Jun 2024; Draft S3R submitted 17 Oct 2024', s3rCategory: 'submitted',
    stlaXpStatus: 'N/A', stlaCategory: 'not-applicable',
    accessPermission: 'De-registration made 26 Jan 2026', accessCategory: 'approved',
    engineeringPlan: 'MR no comment 19 Dec 2024', engineeringPlanCategory: 'approved',
    tprpTwvp: 'N/A', tprpTwvpCategory: 'not-applicable',
    tprpMr: 'N/A', tprpMrCategory: 'not-applicable',
    hsspStatus: 'N/A', hsspCategory: 'not-applicable',
    coordinates: { lat: 22.2760, lng: 114.1810 },
    accepted: false,
  },
];

export const COLORS: Record<string, string> = {
  approved: '#10b981',
  submitted: '#3b82f6',
  pending: '#f59e0b',
  rejected: '#ef4444',
  draft: '#a8a29e',
  'not-applicable': '#d1d5db',
};
